apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build
  namespace: apps
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: jenkins-sa
      restartPolicy: Never
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--context=git://github.com/Tanmoy91/automation-project.git#refs/heads/main"
            - "--dockerfile=helm-charts/my-nginx/Dockerfile"
            - "--destination=docker.io/tanmoyjames/my-nginx:latest"
            - "--cache=true"
          volumeMounts:
            - name: docker-config
              mountPath: /kaniko/.docker/
      volumes:
        - name: docker-config
          secret:
            secretName: dockerhub-secret
            items:
              - key: .dockerconfigjson
                path: config.json
