apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-prometheus" .Release.Name | trunc 63 | trimSuffix "-" }}
spec:
  replicas: {{ .Values.prometheus.replicaCount }}
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.55.0
          ports:
            - containerPort: 9090
